# Generated by Django 5.2.8 on 2025-11-07 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartment_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('area_m2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apartment',
                'ordering': ['entrance', 'floor', 'number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('floors', models.IntegerField()),
            ],
            options={
                'db_table': 'building',
                'ordering': ['number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('entrance_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'entrance',
                'ordering': ['number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'owner',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('spot_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parking_spot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('parking_zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parking_zone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resident_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.TextField()),
                ('contact', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resident',
                'ordering': ['fullname'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResidentialComplex',
            fields=[
                ('complex_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('management', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'residential_complex',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.TextField()),
                ('contact', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('work_schedule', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['fullname'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorageRoom',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('location', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'storage_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В роботі'), ('done', 'Виконано')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='complexes.apartment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='complexes.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_visitors', to=settings.AUTH_USER_MODEL)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='complexes.apartment')),
            ],
        ),
    ]
