# Generated by Django 5.2 on 2025-11-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageroom',
            options={},
        ),
    ]
