# Generated by Django 5.2 on 2025-11-09 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0002_alter_storageroom_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageroom',
            name='storage_id',
        ),
        migrations.AddField(
            model_name='storageroom',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storages', to='complexes.apartment'),
        ),
        migrations.AddField(
            model_name='storageroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storageroom',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storageroom',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='storageroom',
            name='status',
            field=models.CharField(choices=[('free', 'Вільна'), ('occupied', 'Зайнята'), ('reserved', 'Зарезервована')], default='free', max_length=20),
        ),
        migrations.AlterModelTable(
            name='storageroom',
            table=None,
        ),
    ]
