# Generated by Django 5.2 on 2025-11-09 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0003_remove_storageroom_storage_id_storageroom_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageroom',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_rooms', to='complexes.apartment'),
        ),
        migrations.AlterField(
            model_name='storageroom',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='storageroom',
            name='status',
            field=models.CharField(choices=[('free', 'Вільна'), ('occupied', 'Зайнята')], default='free', max_length=20),
        ),
    ]
