# Generated by Django 5.2.8 on 2026-04-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0008_add_relationship_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'managed': False, 'ordering': ['entrance', 'floor', 'number']},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False, 'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='entrance',
            options={'managed': False, 'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='parkingzone',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'managed': False, 'ordering': ['fullname']},
        ),
        migrations.AlterModelOptions(
            name='residentialcomplex',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'managed': False, 'ordering': ['fullname']},
        ),
        migrations.AlterModelOptions(
            name='storageroom',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'managed': False},
        ),
    ]
