# Generated by Django 5.2.8 on 2026-04-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0009_alter_apartment_options_alter_building_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maintenancerequest',
            table='complexes_maintenancerequest',
        ),
        migrations.AlterModelTable(
            name='visitor',
            table='complexes_visitor',
        ),
    ]
