# Generated by Django 5.2.8 on 2026-04-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_access_type_to_staffaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='access_type',
            field=models.CharField(choices=[('guard', 'Охорона'), ('maintenance', 'Техпрацівник')], default='maintenance', max_length=20),
        ),
    ]
